---
- hosts: all
  become: true
  become_user: root
  gather_facts: true
  # TODO read roles from inventory or smth
  roles:
      - whisper
  vars:
      - whisper_github: https://github.com/tiannaru/whisper


